### ISSUE TITLE
How to install Python on Tomato?

### ISSUE THREAD

**Issue by bluepanda999** [ALX1SGit/Tomatoadblock_ui#1]
How did you install Python on Tomato? Python is not available on mine.
Also, you may want to add the required libraries on the instructions as well, flask and flask_googlecharts

**Comment by ALX1SGit** [comment]
> How did you install Python on Tomato? Python is not available on mine.
> Also, you may want to add the required libraries on the instructions as well, flask and flask_googlecharts

Hi, yep you are right. I will I clude libraries that needs to be used

You can use something calles Entware. Is a repo like "apt-get" from linux. You need a router with usb ports in order to have a storage and gives you lot of functionalities.
 Repo information
http://bin.entware.net/armv7sf-k3.2/Packages.html

Guide to install
https://www.linksysinfo.org/index.php?threads/how-to-install-and-run-python-script-on-tomato-usb.68227/
